// Mocks generated by Mockito 5.4.6 from annotations
// in bizagent/test/features/notifications/services/notification_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart'
    as _i2;
import 'package:flutter_local_notifications/src/initialization_settings.dart'
    as _i4;
import 'package:flutter_local_notifications/src/notification_details.dart'
    as _i6;
import 'package:flutter_local_notifications/src/platform_specifics/android/schedule_mode.dart'
    as _i8;
import 'package:flutter_local_notifications_platform_interface/flutter_local_notifications_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:timezone/timezone.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FlutterLocalNotificationsPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterLocalNotificationsPlugin extends _i1.Mock
    implements _i2.FlutterLocalNotificationsPlugin {
  MockFlutterLocalNotificationsPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool?> initialize({
    required _i4.InitializationSettings? settings,
    _i5.DidReceiveNotificationResponseCallback?
        onDidReceiveNotificationResponse,
    _i5.DidReceiveBackgroundNotificationResponseCallback?
        onDidReceiveBackgroundNotificationResponse,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {
            #settings: settings,
            #onDidReceiveNotificationResponse: onDidReceiveNotificationResponse,
            #onDidReceiveBackgroundNotificationResponse:
                onDidReceiveBackgroundNotificationResponse,
          },
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<_i5.NotificationAppLaunchDetails?>
      getNotificationAppLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationAppLaunchDetails,
              [],
            ),
            returnValue: _i3.Future<_i5.NotificationAppLaunchDetails?>.value(),
          ) as _i3.Future<_i5.NotificationAppLaunchDetails?>);

  @override
  _i3.Future<void> show({
    required int? id,
    String? title,
    String? body,
    _i6.NotificationDetails? notificationDetails,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #show,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #notificationDetails: notificationDetails,
            #payload: payload,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancel({
    required int? id,
    String? tag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancel,
          [],
          {
            #id: id,
            #tag: tag,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAll() => (super.noSuchMethod(
        Invocation.method(
          #cancelAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAllPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllPendingNotifications,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> zonedSchedule({
    required int? id,
    required _i7.TZDateTime? scheduledDate,
    required _i6.NotificationDetails? notificationDetails,
    required _i8.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
    _i5.DateTimeComponents? matchDateTimeComponents,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #zonedSchedule,
          [],
          {
            #id: id,
            #scheduledDate: scheduledDate,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
            #matchDateTimeComponents: matchDateTimeComponents,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShow({
    required int? id,
    required _i5.RepeatInterval? repeatInterval,
    required _i6.NotificationDetails? notificationDetails,
    required _i8.AndroidScheduleMode? androidScheduleMode,
    String? title,
    String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShow,
          [],
          {
            #id: id,
            #repeatInterval: repeatInterval,
            #notificationDetails: notificationDetails,
            #androidScheduleMode: androidScheduleMode,
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> periodicallyShowWithDuration({
    required int? id,
    required Duration? repeatDurationInterval,
    required _i6.NotificationDetails? notificationDetails,
    String? title,
    String? body,
    _i8.AndroidScheduleMode? androidScheduleMode =
        _i8.AndroidScheduleMode.exact,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #periodicallyShowWithDuration,
          [],
          {
            #id: id,
            #repeatDurationInterval: repeatDurationInterval,
            #notificationDetails: notificationDetails,
            #title: title,
            #body: body,
            #androidScheduleMode: androidScheduleMode,
            #payload: payload,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.PendingNotificationRequest>>
      pendingNotificationRequests() => (super.noSuchMethod(
            Invocation.method(
              #pendingNotificationRequests,
              [],
            ),
            returnValue: _i3.Future<List<_i5.PendingNotificationRequest>>.value(
                <_i5.PendingNotificationRequest>[]),
          ) as _i3.Future<List<_i5.PendingNotificationRequest>>);

  @override
  _i3.Future<List<_i5.ActiveNotification>> getActiveNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getActiveNotifications,
          [],
        ),
        returnValue: _i3.Future<List<_i5.ActiveNotification>>.value(
            <_i5.ActiveNotification>[]),
      ) as _i3.Future<List<_i5.ActiveNotification>>);
}
