// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'Platform ${defaultTargetPlatform} is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqM76s2ur07H4nthgDHldLPjKuDqd1SOc',
    appId: '1:90348815049:android:eeab2630fb64fc2fd54318',
    messagingSenderId: '90348815049',
    projectId: 'gifted-mountain-476207-u4',
    storageBucket: 'gifted-mountain-476207-u4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIcKfpjs0bidW7XSwVKRybBGrnmwjL0_0',
    appId: '1:90348815049:ios:a4b5f12ee73618f1d54318',
    messagingSenderId: '90348815049',
    projectId: 'gifted-mountain-476207-u4',
    storageBucket: 'gifted-mountain-476207-u4.firebasestorage.app',
    iosBundleId: 'com.bizagent.bizagent',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtiZ0C0hk0BX28v7RXhy1IMzreH2NMTo4',
    appId: '1:90348815049:web:5c0e2e938606a12ad54318',
    messagingSenderId: '90348815049',
    projectId: 'gifted-mountain-476207-u4',
    authDomain: 'gifted-mountain-476207-u4.firebaseapp.com',
    storageBucket: 'gifted-mountain-476207-u4.firebasestorage.app',
  );
}
