// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      default:
        throw UnsupportedError(
          'Platform ${defaultTargetPlatform} is not supported.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjWn54uyCL6YBtsqPCkWpatrwy306rZM',
    appId: '1:542280140779:android:4c205b8194929083373bae',
    messagingSenderId: '542280140779',
    projectId: 'bizagent-live-2026',
    storageBucket: 'bizagent-live-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa8SnnqrxMkJPpKNcZ04v7hKBs-mLN3wM',
    appId: '1:542280140779:ios:5536609225fab278373bae',
    messagingSenderId: '542280140779',
    projectId: 'bizagent-live-2026',
    storageBucket: 'bizagent-live-2026.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZcQ0RbF69p_uA1irgr7-hDkZPF95nSAQ',
    appId: '1:542280140779:web:572f4edccd696c9f373bae',
    messagingSenderId: '542280140779',
    projectId: 'bizagent-live-2026',
    authDomain: 'bizagent-live-2026.firebaseapp.com',
    storageBucket: 'bizagent-live-2026.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}
